---
title: "radio3"
author: "test"
date: "2023-09-06"
output: word_document
---

```{r setup, include=FALSE}

library(ggplot2)
library(dplyr)

```



```{r}
r <- read.csv("test1.csv")
rsel <- r[c("ï..New.IDs","Ra.226..Bq.kg.","Th.232..Bq.kg.", "K.40..Bq.kg.", "Cs.137..Bq.kg.", "Latitude", "Longitude")] %>%
  rename("IDS"= "ï..New.IDs", "Ra-226 (Bq/kg)"= "Ra.226..Bq.kg.", "Th-232 (Bq/kg)
"="Th.232..Bq.kg.", "K-40 (Bq/kg)
"="K.40..Bq.kg.", "Cs-137 (Bq/kg)
"="Cs.137..Bq.kg.", "Latitude"="Latitude", "Longitude"= "Longitude")
```



```{r}
ra <- ggplot(rsel,aes(y=`Ra-226 (Bq/kg)`))+
      geom_boxplot(color="red",outlier.color="black")
ra
```


```{r}
boxplot(rsel$`Ra-226 (Bq/kg)`,ylab="Ra-226(Bq/kg)")
```



```{r}
th <- ggplot(rsel,aes(y= rsel$`Th-232 (Bq/kg)`))+
      geom_boxplot(color="red",outlier.color="black")
th
```



```{r}
boxplot(rsel$`Th-232 (Bq/kg)`,ylab="Th-232 (Bq/kg)")

```



```{r}
k <- ggplot(rsel,aes(y= rsel$`K-40 (Bq/kg)`))+
      geom_boxplot(color="red",outlier.color="black")
k
```



```{r}
boxplot(rsel$`K-40 (Bq/kg)`,ylab="K-40 (Bq/kg)")

```




```{r}
cs <- ggplot(rsel, aes(y= rsel$`Cs-137 (Bq/kg)`)) + 
  geom_boxplot(color="red",outlier.color="black")
  

#cs <- ggplot(rsel,aes(y= rsel$`Cs-137 (Bq/kg)`))+
      #geom_boxplot(color="red",outlier.color="black")
cs
```



```{r}
boxplot(rsel$`Cs-137 (Bq/kg)`,ylab="Cs-137 (Bq/kg)")

```



```{r}
library(RColorBrewer)
myPalette <- colorRampPalette(rev(brewer.pal(11, "Spectral")))      # Create reverse Spectral palette


plot <- ggplot() +
  geom_polygon(data = rsel, aes(fill = rsel$`Cs-137 (Bq/kg)`,   
                                         x = IDS, 
                                         y = rsel$`Cs-137 (Bq/kg)`, 
                                         group = IDS)) +      # Dummy variable to correct fill by PCode.
  scale_fill_gradientn(colours=myPalette(4)) +                 # Choose palette colours.
  labs(fill="rsel$`Cs-137 (Bq/kg)`")
plot(plot)
```



```{r}
rsel2 <- rsel %>%
  drop_na(Longitude)
# x, y, z variables
x <- rsel2$`Ra-226 (Bq/kg)`
y <- rsel2$`Th-232 (Bq/kg)`
z <- rsel2$`Cs-137 (Bq/kg)`
# Compute the linear regression (z = ax + by + d)
fit <- lm(z ~ x + y)
# predict values on regular xy grid
grid.lines = 26
x.pred <- seq(min(x), max(x), length.out = grid.lines)
y.pred <- seq(min(y), max(y), length.out = grid.lines)
xy <- expand.grid( x = x.pred, y = y.pred)
z.pred <- matrix(predict(fit, newdata = xy), 
                 nrow = grid.lines, ncol = grid.lines)
# fitted points for droplines to surface
fitpoints <- predict(fit)
# scatter plot with regression plane
plot3d(x, y, z, pch = 18, cex = 2, 
    theta = 20, phi = 20, ticktype = "detailed",
    xlab = "ra", ylab = "th", zlab = "cs137",  
    surf = list(x = x.pred, y = y.pred, z = z.pred,  
    facets = NA, fit = fitpoints), main = "scatterplot3d")
```



```{r}
persp(x, y, z)
```

